### ISSUE TITLE
Impact of changes since Sinova fork (2.5.4?) - particularly performance-wise

### ISSUE THREAD

**Issue by mdealiaga** [Prozi/detect-collisions#27]
First of all thank you for updating and continuing support on this project!

I'm currently using the original 2.5 fork and was pleasantly surprised to see this library has been upgraded in the last year.

I'm mainly wondering about the performance impact of the change to RBush/SAT https://github.com/Prozi/detect-collisions/releases/tag/v3.0.2 as my use-case (high entity count multiplayer game server) is really CPU intensive.

I'm also wondering if there is a list of breaking changes to be aware of when updating the API - there is a header for "BREAKING CHANGES" in the v3 patch notes but no note of them.

**Comment by Prozi** [comment]
the breaking changes summarised:

first parameter of `new Point|Circle|Polygon` is now a `{ x, y } Vector`

also the polygon's points array is filled with `{ x, y }` instead of `[x, y]`

**creating bodies**

v2:

```
const { Collisions, Circle, Polygon, Point } = require('detect-collisions');

const system  = new Collisions();
const circle  = new Circle(100, 100, 10);
const polygon = new Polygon(50, 50, [[0, 0], [20, 20], [-10, 10]]);

system.insert(circle)
system.insert(polygon);
```

v3+

```
const { System, Circle, Polygon, Point } = require('detect-collisions');

const system = new System();
const circle = new Circle({ x: 100, y: 100 }, 10);
const polygon = new Polygon({ x: 50, y: 50 }, [
  { x: 0, y: 0 },
  { x: 20, y: 20 },
  { x: -10, y: 10 },
]);

system.insert(circle)
system.insert(polygon);
```

**testing for collisions**

v2

```
const potentials = polygon.potentials();

for (const body of potentials) {
	if (polygon.collides(body)) {
		console.log('Collision detected!');
	}
}
```

v3+

```
system.checkAll(handleCollisions);
```

or

```
system.checkOne(body, handleCollisions)
```

or

```
system.getPotentials(body).forEach((collider) => {
  if (system.checkCollision(body, collider)) {
    handleCollisions(system.response);
  }
});
```

where handleCollisions is a handler like

```
function handleCollisions(response: SAT.Response) {
  // your logic
}
```

see https://github.com/jriecken/sat-js#satresponse

**Comment by Prozi** [comment]
the performance differences are minimal I think, because I've kept the demos and their results are the same

I will do some kind of benchmark of `latest` vs `v2` version to see the exact times

**Comment by Prozi** [comment]
also since v3 there has been a number of improvements:

- the library is now typescript transpiled to js with types
- uses npm package sat for Separating Axes Theorem which is a popular and maintained library instead of using what was written in v1 version
- uses npm package rbush for Bounding Volume Hierarchy which for same reason as above one
- has raycast support (see https://github.com/Prozi/detect-collisions#raycast) which was a requested feature
- kept the demos, updated with new apis
- added quite a few tests and continuous integration

@mdealiaga

**Comment by mdealiaga** [comment]
Thank you for the rundown @Prozi ! I will aim to upgrade soon. Typescript support and raycasting will be very useful.

It would definitely be interesting to benchmark these libraries, also alongside some of the main JS physics engines (p2js etc).

**Comment by mdealiaga** [comment]
Hi, one additional question: was support removed for padding via these updates? (https://github.com/Sinova/Collisions#anchor-bounding-volume-padding)

I currently use that for all my moving entities -- I did not rigorously test the performance increase, but it made sense to apply this to entities expected to move every server update.

**Comment by mdealiaga** [comment]
Thank you for the quick patch with this feature!
