### ISSUE TITLE
Types: improvement

### ISSUE THREAD

**Issue by Mero-Plaform** [Prozi/detect-collisions#55]
Add **explicit** params **types** for **system.create*** functions

otherways, user will need to make unnessecary types declarations, to setup types 

such as:

```
export type BoxParams = {
  height: number;
  width: number;
  vector: Vector;
  options?: BodyOptions;
};

...

addBox({ ... }: BoxParams) {
  ...
}
```

or getting them by hard manipulations, using other TS Utilities

**Comment by Prozi** [comment]
hello @Mero-Plaform  and thanks for opening an issue

did you see https://github.com/Prozi/detect-collisions#3-create-and-insert-body or https://prozi.github.io/detect-collisions/classes/System.html#createBox ?

the type you're looking for is BodyOptions https://prozi.github.io/detect-collisions/interfaces/BodyOptions.html

**Comment by Mero-Plaform** [comment]
BodyOption contains only: angle, isCentered, isStatic, isTrigger, padding

but not the main props, such as vectors, height & width

like:
- position, width, height for createBox
- position, radius for createCircle
etc...

**Comment by Prozi** [comment]
> BodyOption contains only: angle, isCentered, isStatic, isTrigger, padding
> 
> but not the main props, such as vectors, height and so on
> 
> like:
> 
> * position, width, height for **createBox**
> * position, radius for **createCircle**
>   etc...

createBox(position: [PotentialVector](https://prozi.github.io/detect-collisions/interfaces/PotentialVector.html), width: number, height: number, options?: [BodyOptions](https://prozi.github.io/detect-collisions/interfaces/BodyOptions.html)): [Box](https://prozi.github.io/detect-collisions/classes/Box.html)

createCircle(position: [PotentialVector](https://prozi.github.io/detect-collisions/interfaces/PotentialVector.html), radius: number, options?: [BodyOptions](https://prozi.github.io/detect-collisions/interfaces/BodyOptions.html)): [Circle](https://prozi.github.io/detect-collisions/classes/Circle.html)

the exact types for create* functions are there and are also documented

what is missing here?

I am missing the issue here

**Comment by Prozi** [comment]
once again I point to https://prozi.github.io/detect-collisions/classes/System.html documentation of API

**Comment by Prozi** [comment]
also note that

```
const box = new Box(position, width, height, options)
```

Box takes 4 parameters for constructor, from which last is optional

it is also noted here https://prozi.github.io/detect-collisions/classes/Box.html#constructor

it doesn't take one argument like you wrote:
```
addBox({ ... }: BoxParams) {
```

**Comment by Mero-Plaform** [comment]
I thought it over, it can't be solve the way I mean it, so I'm closing the issue
